"""
Module for Managing and Pairing Stereo Images and Videos
====================================================================
Provides the functions and data structures for scanning capture folders,
temporal pairing of stereo frames/videos
(Right Camera / Left Camera) and dataset integrity checks
— including rejection of folder formats meant for another
page (e.g. an rx/lx folder mistakenly used in Photo Analysis).

Expected format for STEREO PAIRS (photos or videos): subfolders "rx/" and
"lx/" (or "right/"/"left/") inside the chosen folder — exactly as
generated by the Sensing-Rigs daemon on Raspberry Pi (see constants.c:
DAEMON_PATH_CAP="captures/", DAEMON_PATH_RX="rx/", DAEMON_PATH_LX="lx/").
For photos, the files inside rx/lx are named with only the Unix timestamp
epoch (e.g. "1723130400.jpg"); for videos, each subfolder contains
a single video file.

Autore: Samuele Gallo
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tiff"}
VIDEO_EXTENSIONS = {".mp4", ".avi", ".mov", ".mkv"}

# We keep the historical name used elsewhere in the code.
VALID_EXTENSIONS = IMAGE_EXTENSIONS

_RIGHT_DIR_NAMES = ("rx", "right", "r")
_LEFT_DIR_NAMES = ("lx", "left", "l")


def is_stereo_dataset_folder(folder: Path) -> bool:
    """
    True if the folder is in the "stereo pair" format (contains BOTH the
    rx/lx or right/left subfolders) — regardless of whether it contains
    photos or a video. Used to prevent the same folder format
    from being used by mistake in a different page (Photo Analysis
    wants FLAT image folders, not rx/lx).
    """
    folder = Path(folder)
    if not folder.is_dir():
        return False
    names = {p.name.lower() for p in folder.iterdir() if p.is_dir()}
    return bool(names & set(_RIGHT_DIR_NAMES)) and bool(names & set(_LEFT_DIR_NAMES))


def _find_side_dirs(target_directory: Path) -> Tuple[Optional[Path], Optional[Path]]:
    """Looks for rx/lx (or right/left) subfolders inside target_directory."""
    right_dir = next(
        (p for p in target_directory.iterdir() if p.is_dir() and p.name.lower() in _RIGHT_DIR_NAMES),
        None,
    )
    left_dir = next(
        (p for p in target_directory.iterdir() if p.is_dir() and p.name.lower() in _LEFT_DIR_NAMES),
        None,
    )
    if right_dir is not None and left_dir is not None:
        return right_dir, left_dir
    return None, None


@dataclass(frozen=True)
class StereoPair:
    """Represents a pair of stereo images linked by the same timestamp."""
    timestamp: str
    right_path: Path
    left_path: Path


class StereoPairFinder:
    """
    Class for identifying and pairing the stereo images
    found in the rx/lx subfolders of a capture folder.
    Used ONLY by Stereo Analysis (photos): explicitly rejects a
    folder that is not in the rx/lx format, so a folder meant for
    Photo Analysis cannot be chosen by mistake.
    """

    def __init__(self, target_directory: Path) -> None:
        self.target_directory = Path(target_directory)

    def scan_and_pair(self) -> List[StereoPair]:
        """
        Scans the specified directory, finds the rx/lx subfolders,
        and returns the list of pairs with a matching timestamp in both.
        """
        if not self.target_directory.is_dir():
            raise FileNotFoundError(f"La directory specificata non esiste: {self.target_directory}")

        right_dir, left_dir = _find_side_dirs(self.target_directory)
        if right_dir is None or left_dir is None:
            raise FileNotFoundError(
                f"Sottocartelle rx/lx (o right/left) non trovate in: {self.target_directory}\n"
                f"Questa cartella non e' nel formato atteso dall'Analisi Stereo."
            )

        return self._pair_from_side_dirs(right_dir, left_dir)

    @staticmethod
    def _pair_from_side_dirs(right_dir: Path, left_dir: Path) -> List[StereoPair]:
        """Pairs the files of two subfolders by their shared name (stem)."""

        def _index(directory: Path) -> Dict[str, Path]:
            return {
                f.stem: f
                for f in directory.iterdir()
                if f.is_file() and f.suffix.lower() in IMAGE_EXTENSIONS
            }

        right_images = _index(right_dir)
        left_images = _index(left_dir)

        common_timestamps = sorted(set(right_images.keys()) & set(left_images.keys()))

        return [
            StereoPair(timestamp=ts, right_path=right_images[ts], left_path=left_images[ts])
            for ts in common_timestamps
        ]


@dataclass(frozen=True)
class SingleImageItem:
    """A single image of a sequence (Photo Analysis folder), with its name/timestamp."""
    timestamp: str
    image_path: Path


class SingleImageFinder:
    """
    Scans a FLAT folder of images (no rx/lx subfolders) and
    sorts them by file name, treating them as a sequence — like the frames
    of a video, but already on disk. Used by Photo Analysis (Single mode).
    Explicitly rejects a folder in rx/lx format: that format is
    reserved for Stereo Analysis and must not be reused here by mistake.
    """

    def __init__(self, target_directory: Path) -> None:
        self.target_directory = Path(target_directory)

    def scan(self) -> List[SingleImageItem]:
        if not self.target_directory.is_dir():
            raise FileNotFoundError(f"La directory specificata non esiste: {self.target_directory}")

        if is_stereo_dataset_folder(self.target_directory):
            raise ValueError(
                f"'{self.target_directory.name}' e' una cartella in formato stereo (contiene rx/lx): "
                f"usala nella pagina Analisi Stereo, non qui."
            )

        files = sorted(
            (f for f in self.target_directory.iterdir() if f.is_file() and f.suffix.lower() in IMAGE_EXTENSIONS),
            key=lambda f: f.stem,
        )
        return [SingleImageItem(timestamp=f.stem, image_path=f) for f in files]


def find_single_video(target_directory: Path) -> Path:
    """
    Looks for exactly ONE video file directly inside target_directory (Video
    Analysis, Single mode). Rejects a folder in stereo format
    (rx/lx): that format is for Stereo Video mode, not this one.
    """
    target_directory = Path(target_directory)
    if not target_directory.is_dir():
        raise FileNotFoundError(f"La directory specificata non esiste: {target_directory}")

    if is_stereo_dataset_folder(target_directory):
        raise ValueError(
            f"'{target_directory.name}' e' una cartella in formato stereo (contiene rx/lx): "
            f"usala nella modalita' Video Stereo, non qui."
        )

    videos = sorted(
        f for f in target_directory.iterdir() if f.is_file() and f.suffix.lower() in VIDEO_EXTENSIONS
    )
    if not videos:
        raise FileNotFoundError(f"Nessun file video trovato in: {target_directory}")

    return videos[0]


@dataclass(frozen=True)
class StereoVideoPair:
    """Represents the pair of synchronized video files (right/left) of a stereo dataset."""
    right_video: Path
    left_video: Path


def find_stereo_video_pair(target_directory: Path) -> StereoVideoPair:
    """
    Looks for a pair of synchronized videos in the rx/lx subfolders of
    target_directory (Video Analysis, Stereo mode) — a single video file
    per subfolder. Explicitly rejects a folder that is NOT in the
    rx/lx format (that is Single Video mode).
    """
    target_directory = Path(target_directory)
    if not target_directory.is_dir():
        raise FileNotFoundError(f"La directory specificata non esiste: {target_directory}")

    right_dir, left_dir = _find_side_dirs(target_directory)
    if right_dir is None or left_dir is None:
        raise FileNotFoundError(
            f"Sottocartelle rx/lx (o right/left) non trovate in: {target_directory}\n"
            f"La modalita' Video Stereo richiede due video sincronizzati in rx/ e lx/."
        )

    def _first_video(directory: Path) -> Path:
        videos = sorted(f for f in directory.iterdir() if f.is_file() and f.suffix.lower() in VIDEO_EXTENSIONS)
        if not videos:
            raise FileNotFoundError(f"Nessun file video trovato in: {directory}")
        return videos[0]

    return StereoVideoPair(right_video=_first_video(right_dir), left_video=_first_video(left_dir))
