"""
Utility Module for Capturing Stereo Test Pairs
==============================================
Allows guided, timed recording of stereo frames
from two camera modules (Right / Left) for testing the metrological pipeline.

Each run creates a new "testN" folder (incremental) inside
datasets/, so the captures automatically show up in the app's
"Dataset folder" drop-down without having to add them manually.

The output format replicates EXACTLY that of the Sensing-Rigs daemon
(see constants.c: DAEMON_PATH_CAP="captures/", DAEMON_PATH_RX="rx/",
DAEMON_PATH_LX="lx/", file name = Unix epoch timestamp, e.g. "1723130400.jpg"):

    datasets/Dataset_Locale/dataset_Foto_Stereo/testN/
    ├── rx/
    │   ├── 1723130400.jpg
    │   └── 1723130403.jpg
    └── lx/
        ├── 1723130400.jpg
        └── 1723130403.jpg

Autore: Candidato Tesi
"""

from __future__ import annotations

import re
import time
from pathlib import Path

import cv2

# --- DEVICE CONFIGURATION AND CAPTURE PARAMETERS ---
# Note: these indices refer to the webcams connected to the development
# machine (they do not necessarily match the camera indices 0/1 used
# by the daemon on the Raspberry, which are a hardware detail of the Pi).
CAM_RIGHT_INDEX: int = 0
CAM_LEFT_INDEX: int = 1

FRAME_WIDTH: int = 1280
FRAME_HEIGHT: int = 720

TOTAL_CAPTURES: int = 20
INTERVAL_SECONDS: float = 3.0

# Folder collecting all datasets (same one used by the app's GUI)
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from common.paths import STEREO_PHOTO_DIR as DATASETS_DIR  # noqa: E402

_TEST_DIR_PATTERN = re.compile(r"^test(\d+)$")


def _get_next_test_dir(base_dir: Path) -> Path:
    """Determines the next free 'testN' name and creates the corresponding folder."""
    base_dir.mkdir(parents=True, exist_ok=True)

    max_n = 0
    for entry in base_dir.iterdir():
        if entry.is_dir():
            match = _TEST_DIR_PATTERN.match(entry.name)
            if match:
                max_n = max(max_n, int(match.group(1)))

    new_dir = base_dir / f"test{max_n + 1}"
    new_dir.mkdir(parents=True, exist_ok=False)
    return new_dir


def run_test_capture() -> None:
    """Runs the automatic capture loop for stereo image pairs."""
    output_dir = _get_next_test_dir(DATASETS_DIR)
    rx_dir = output_dir / "rx"
    lx_dir = output_dir / "lx"
    rx_dir.mkdir(parents=True, exist_ok=True)
    lx_dir.mkdir(parents=True, exist_ok=True)

    cap_right = cv2.VideoCapture(CAM_RIGHT_INDEX)
    cap_left = cv2.VideoCapture(CAM_LEFT_INDEX)

    for cap in (cap_right, cap_left):
        cap.set(cv2.CAP_PROP_FRAME_WIDTH, FRAME_WIDTH)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, FRAME_HEIGHT)

    captures_count: int = 0
    last_capture_time: float | None = None
    is_active: bool = False
    status_message: str = "Premi SPAZIO per iniziare  |  Q per uscire"

    print(f"[INFO] Le coppie verranno salvate in: {output_dir}  (formato rx/lx, come il demone reale)")
    print("[INFO] Finestre di acquisizione aperte. Premi SPAZIO per avviare il timer.")

    try:
        while captures_count < TOTAL_CAPTURES:
            ret_r, img_right = cap_right.read()
            ret_l, img_left = cap_left.read()

            if not ret_r or not ret_l:
                print("[ERROR] Impossibile acquisire il flusso da una o entrambe le telecamere.")
                break

            now = time.time()

            # Timed automatic shot
            if is_active and (last_capture_time is None or (now - last_capture_time) >= INTERVAL_SECONDS):
                # Unix epoch timestamp (integer), as generated by rpicam-still with --timestamp
                epoch_ts = int(now)

                path_r = rx_dir / f"{epoch_ts}.jpg"
                path_l = lx_dir / f"{epoch_ts}.jpg"

                cv2.imwrite(str(path_r), img_right)
                cv2.imwrite(str(path_l), img_left)

                captures_count += 1
                last_capture_time = now
                status_message = "Riposizionare il target..."
                print(f"[{captures_count}/{TOTAL_CAPTURES}] Acquisita coppia: {epoch_ts}")

            display_r = img_right.copy()
            display_l = img_left.copy()

            # Countdown calculation
            if is_active and last_capture_time is not None:
                time_remaining = INTERVAL_SECONDS - (now - last_capture_time)
                if time_remaining > 0:
                    status_message = f"Prossimo scatto tra {time_remaining:.1f}s  |  Muovere il target"

            # Info bar rendering (Right Camera)
            cv2.rectangle(display_r, (0, 0), (FRAME_WIDTH, 50), (0, 0, 0), -1)
            cv2.putText(
                display_r,
                f"Scatti: {captures_count}/{TOTAL_CAPTURES}  |  {status_message}",
                (10, 33),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.6,
                (0, 255, 0),
                2,
            )

            # Info bar rendering (Left Camera)
            cv2.rectangle(display_l, (0, 0), (FRAME_WIDTH, 50), (0, 0, 0), -1)
            cv2.putText(
                display_l,
                "CAMERA SINISTRA (L)",
                (10, 33),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.6,
                (0, 200, 255),
                2,
            )

            # Visual feedback for the shot taken (green flash)
            if last_capture_time is not None and (now - last_capture_time) < 0.4:
                cv2.rectangle(display_r, (0, 0), (FRAME_WIDTH, FRAME_HEIGHT), (0, 255, 0), 8)
                cv2.rectangle(display_l, (0, 0), (FRAME_WIDTH, FRAME_HEIGHT), (0, 255, 0), 8)
                cv2.putText(
                    display_r,
                    "ACQUISITO",
                    (450, 390),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1.8,
                    (0, 255, 0),
                    4,
                )

            cv2.imshow("Acquisizione Stereo - Camera Destra (R)", display_r)
            cv2.imshow("Acquisizione Stereo - Camera Sinistra (L)", display_l)

            key = cv2.waitKey(1) & 0xFF
            if key == ord("q") or key == ord("Q"):
                break
            if key == ord(" ") and not is_active:
                is_active = True
                last_capture_time = None
                status_message = "Acquisizione avviata"
                print("[INFO] Sequenza di acquisizione temporizzata avviata.")

    finally:
        cap_right.release()
        cap_left.release()
        cv2.destroyAllWindows()
        print(f"\n[INFO] Procedura terminata. {captures_count} coppie salvate in: {output_dir}")


if __name__ == "__main__":
    run_test_capture()